var tux = [
'                                    ttDDKKKKKKGGjj',
'                                ;;WW################ff',
'                              ..######################DD',
'                              GG################GG;;####ff',
'                              ##################EE######WW',
'                            ;;############################ii',
'                            ii############################jj',
'                            tt##KK  KK######tt  iiWW######LL',
'                            tt##      ####GG       i######GG',
'                            ttWW GEE  WW##tt  WWLL  ######DD',
'                            ii## GKK LKK##ttDD##KK  KK####EE',
'                            ii##iiKKLL;;;;jjff##WW..WW####KK',
'                            ;;##DD            iiGGWW########',
'                            ;;##                  ..WW######::',
'                            ..##LL             jGGii########ff',
'                            ..####GGt      Gffiijjtt##WWttWWWW',
'                              ##WWKKLLLLjj;;ffKKff  ####LLff##ff',
'                            ff##  ##DDffGGWWLL      GG########WW..',
'                          ;;##LL  tt######ii          WW########LL',
'                          KK##::    iiff              tt##########;;',
'                        LL##GG                          ##########WW',
'                      ii####tt                          EE##WW######GG',
'                      WW####ii                          ff####ff######jj',
'                    DDKK####ii                            WW##KKLL######',
'                  ;;##LL##GG                              tt####ffWW####GG',
'                  LLWW####                                  WW##WW  ######;;',
'                  WW####GG                                  ff####  ######LL',
'                tt######ii                                  ;;####G  D####WW',
'                EEWW##WW                                      ####WW  ######;;',
'              ;;##D ##DD                                      ######  ######jj',
'              EE## G##LL                                      ####WW  ######GG',
'            ii#### G##ff                                      ####D  W######KK',
'            ff#### L##ff                                      DDKK  EE######WW',
'            LL####K  tii                                      ffWW##EEKK####WW',
'            iijjjjWWDD                                      ii##############GG',
'            ii    ;;WWKK                                  KKLL############WW',
'          iiff      tt##KK                                GG  GG########WW;;;;',
'          KKii        ff##WWii                            LL  ;;KK####DD;;  jjii',
'  LLLLGGDDjj            DD####jj                          LL      tt;;      jjff',
'  DD                    ;;######LL                        DD                ;;##;;',
'  WW;;                    jj######                      ;;KK                  GGWWii',
'  DDff                      DD##WW                    LLtt##                    ;;ffLL',
'  LLGG                      ;;KK                    tt##ff##                        GG;;',
'  DDff                        GGiiLL              LL####ttWW                      ttLL',
'  KK;;                        iiWWii##GGLLLLGGKK######KKjjKK                ;;ffDDtt',
';;DDii                          ##tt##################GGLLDD            iiDDWWff',
'  jjKKWWDDff;;                tt##DD##################WWKKKK          jj##LL',
'        iiffGGKKDDfftt        DD##EEffttttiiiiiiiittttttWW##jj      GG##ii',
'                ;;LL##WWDDDDKKWWii                      ii####KKDDWW##;;',
'                      ttDDWWDD                            iiGGKKKKGG'
];
